{{- range $key, $value := .Values.roleBindings }}
{{- if $value.createBinding | default true }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if $value.scope.cluster }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ $.Values.name }}
subjects:
- kind: {{ $value.subjects.kind | default "ServiceAccount" }}
  name: {{ $.Values.name }}-sa
  namespace: {{ $.Values.namespace }}
  apiGroup: {{ $value.subjects.apiGroup | quote }}
roleRef:
{{- if $value.scope.cluster }}
  kind: ClusterRole
{{- else }}
  kind: Role
{{- end }}
  name: {{ $.Values.name }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}
