{{- range $key, $value := .Values.roles }}
{{- if $value.createRole | default true }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if $value.scope.cluster }}
kind: ClusterRole
metadata:
  name: {{ $.Values.name }}-clr
{{- else }}
kind: Role
metadata:
  name: {{ $.Values.name }}-role
{{- end }}
rules:
  - apiGroups:
{{- range $value.apiGroups }}
      - {{ . | quote }}
{{- end }}
    resources:
{{- range $value.resources }}
      - {{ . | quote }}
{{- end }}
    verbs:
{{- range $value.verbs }}
      - {{ . }}
{{- end }}
{{- end }}
{{- end }}